App.PL/Controllers/DepartmentController.cs
using App.BLL.Interfaces;
using App.DAL.Models;
using App.PL.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using System;
using System.Collections.Generic;

namespace App.PL.Controllers
{
	[Authorize]

	public class DepartmentController : Controller
	{
		private readonly IDepartmentRepository departmentRepository;
        private readonly IUnitOfWork unitOfWork;
        private readonly IWebHostEnvironment _env;
		private readonly IMapper mapper;

		public DepartmentController(IUnitOfWork unitOfWork , IWebHostEnvironment env , IMapper mapper ) {
            this.unitOfWork = unitOfWork;
			this.departmentRepository = unitOfWork.departmentRepository;
            _env = env;
			this.mapper = mapper;
		}

		#region Create Department

		[HttpGet]
		[AutoValidateAntiforgeryToken]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[AutoValidateAntiforgeryToken]
		public IActionResult Create(DepartmentViewModel newD)
		{
			if (!ModelState.IsValid)
			{
				return BadRequest(ModelState);
			}
			try
			{
				var department = mapper.Map<DepartmentViewModel, Department>(newD);
                departmentRepository.Add(department);
                unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
			}
			catch(Exception ex)
			{
                if (_env.IsDevelopment())
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "There is error occured during ubdate ");
                }
                return View(newD);
			}
		}
		#endregion

		#region Edit Department
		[HttpGet]
		[AutoValidateAntiforgeryToken]
		public IActionResult Edit(int? id)
		{
			if (id == null || !id.HasValue)
			{
				return View("Error");
			}
			var Department = departmentRepository.GetByID(id.Value);
			var DepartmentVM = mapper.Map< Department,DepartmentViewModel> (Department);
			return View(DepartmentVM);
		}
		[HttpPost]
		[AutoValidateAntiforgeryToken]
		public IActionResult Edit([FromRoute] int id, DepartmentViewModel D)
		{
			if (!ModelState.IsValid)
			{
				return View(D);
			}
			if (id != D.ID)
			{
				return BadRequest();
			}
			try
			{
				var department = mapper.Map<DepartmentViewModel, Department >(D);
				departmentRepository.Update(department);
                unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				if (_env.IsDevelopment())
				{
					ModelState.AddModelError(string.Empty, ex.Message);
				}
				else
				{
					ModelState.AddModelError(string.Empty, "There is error occured during ubdate ");
				}
				return View(D);
			}
		}
		#endregion

		#region Delete Department
		[AutoValidateAntiforgeryToken]
		public IActionResult Delete(int? id)
		{
			if (id == null || !id.HasValue)
			{
				return View("Error");
			}
			var Department = departmentRepository.GetByID(id.Value);
			var DepartmentViewModel = mapper.Map<Department , DepartmentViewModel>(Department);
			return View(DepartmentViewModel);
		}
		[HttpPost]
		[AutoValidateAntiforgeryToken]
		public IActionResult Delete([FromRoute] int id, DepartmentViewModel D)
		{
			if (!ModelState.IsValid)
			{
				return View(D);
			}
			if (id != D.ID)
			{
				return BadRequest();
			}
			try
			{
				var department = mapper.Map<DepartmentViewModel, Department>(D);

                departmentRepository.Delete(department);
                unitOfWork.Complete();
				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				if (_env.IsDevelopment())
				{
					ModelState.AddModelError(string.Empty, ex.Message);
				}
				else
				{
					ModelState.AddModelError(string.Empty, "There is error occured during ubdate ");
				}
				return View(D);
			}
		}
		#endregion

		#region Department Details 
		[AutoValidateAntiforgeryToken]
		public IActionResult Details(int? id)
		{
			if (id == null || !id.HasValue)
			{
				return View("Error");
			}
			var Department = departmentRepository.GetByID(id.Value);
			var DepartmentVM = mapper.Map<Department,DepartmentViewModel>(Department);
			return View(DepartmentVM);
		}

		#endregion
		public IActionResult Index()
		{
			var Departments = departmentRepository.GetAll();
			var DepartmentsVM = mapper.Map< IEnumerable<Department>,  IEnumerable< DepartmentViewModel>> (Departments);
			return View(DepartmentsVM);
		}
	}
}

App.PL/Controllers/UserController.cs
using App.DAL.Models;
using App.PL.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace App.PL.Controllers
{
	public class UserController : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly RoleManager<IdentityRole> _roleManager;

		public UserController(UserManager<ApplicationUser> userManager , RoleManager<IdentityRole> roleManager)
        {
			_userManager = userManager;
			_roleManager = roleManager;
		}

		#region Details Of User Action
		public async Task<IActionResult> Details(string id)
		{
			if (id == null)
			{
				return NotFound();
			}
			var User = await _userManager.FindByIdAsync(id);
			if (User == null)
			{
				return NotFound();
			}
			var MappedUser = new UserViewModel()
			{
				Id = User.Id,
				Email = User.Email,
				FullName = User.Fname + " " + User.Lname,
				Roles = _userManager.GetRolesAsync(User).Result,
			};
			return View(MappedUser);
		}

		#endregion

		public IActionResult Edit()
		{
			return View();
		}

		//public IActionResult Edit(UserViewModel model) {
				
		//}

		#region Get All And Search Action
		public async Task<IActionResult> Index(string email)
		{
			if (email == null)
			{
				var Users = await _userManager.Users.Select(User => new UserViewModel
				{
					Id = User.Id,
					Email = User.Email,
					FullName = User.Fname + " " + User.Lname,
					Roles = _userManager.GetRolesAsync(User).Result,
				}).ToListAsync();
				return View(Users);
			}
			else
			{
				var User = await _userManager.FindByEmailAsync(email);
				if (User == null)
				{
					return NotFound();
				}
				var MappedUser = new UserViewModel()
				{
					Id = User.Id,
					Email = User.Email,
					FullName = User.Fname + " " + User.Lname,
					Roles = _userManager.GetRolesAsync(User).Result,
				};
				return View(new List<UserViewModel>() { MappedUser });
			}
			return View();
		} 
		#endregion

	}
}

App.PL/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - App.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUD system</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignUp">Sign Up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Sign in</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Ahmed Amr - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

App.PL/Views/Shared/_ButtonsPartial.cshtml
@model string;
<td> <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@Model">Delete</a> </td>
<td> <a class="btn btn-info text-white " asp-action="Edit" asp-route-id="@Model">Update</a> </td>
<td> <a class="btn btn-primary text-white " asp-action="Details" asp-route-id="@Model">Details</a> </td>

App.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - App.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUD system</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav  ms-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>
                      
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Ahmed Amr - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("validate", required: false)

</body>
</html>